export const wards = [
    "1 - Etobicoke North",
    "2 - Etobicoke Centre",
    "3 - Etobicoke-Lakeshore",
    "4 - Parkdale-High Park",
    "5 - York South-Weston",
    "6 - York Centre",
    "7 - Humber River-Black Creek",
    "8 - Eglinton-Lawrence",
    "9 - Davenport",
    "10 - Spadina-Fort York",
    "11 - University-Rosedale",
    "12 - Toronto-St. Paul's",
    "13 - Toronto Centre",
    "14 - Toronto-Danforth",
    "15 - Don Valley West",
    "16 - Don Valley East",
    "17 - Don Valley North",
    "18 - Willowdale",
    "19 - Beaches-East York",
    "20 - Scarborough Southwest",
    "21 - Scarborough Centre",
    "22 - Scarborough-Agincourt",
    "23 - Scarborough North",
    "24 - Scarborough-Guildwood",
    "25 - Scarborough-Rouge Park",
];
